name: Linting Frontend Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    permissions:
      contents: read
      packages: read

      pull-requests: read
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./backend

      - name: Install Dependencies
        run: npm ci

      - name: Save Linting Report
        run: |
          npm run lint
        continue-on-error: true

      - name: Annotate Code
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: "./backend/backendReport.json"
          markdown-report-on-step-summary: true
