name: Make a release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker meta frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-frontend
          tags: |
              type=semver,pattern={{version}},prefix=v

      - name: Build frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}

      - name: Docker meta backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-backend
          tags: |
              type=semver,pattern={{version}},prefix=v

      - name: Build backend
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
